ICT2106_WithAction/Models/Cameras/CameraFactory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Cameras
{
    public class CameraFactory : ICategoryFactory
    {
        public IGeneralValue setGeneralValue(int actionID, string actionName, string category, int deviceID, string deviceName)
        {
            return new CameraGeneral(actionID, actionName, category, deviceID, deviceName);
        }

        public IPropertyValue setPropertyValues(List<string> propertyList, List<string> propertyName)
        {
            return new CameraValue(propertyList, propertyName);
        }
    }
}

ICT2106_WithAction/Models/Cameras/CameraGeneral.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Cameras
{
    class CameraGeneral : IGeneralValue
    {
        private int actionID;
        private string actionName;
        private string category;
        private int deviceID;
        private string deviceName;

        public CameraGeneral(int actionID, string actionName, string category, int deviceID, string deviceName)
        {
            this.actionID = actionID;
            this.actionName = actionName;
            this.category = category;
            this.deviceID = deviceID;
            this.deviceName = deviceName;
        }

        public int getActionID()
        {
            return actionID;
        }

        public string getActionName()
        {
            return actionName;
        }

        public string getCategory()
        {
            return category;
        }

        public int getDeviceID()
        {
            return deviceID;
        }

        public string getDeviceName()
        {
            return deviceName;
        }
    }
}

ICT2106_WithAction/Models/Cameras/CameraModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Cameras
{
    public class CameraModel: ICategoryPropertyType
    {
        private const string status = "Status";
        private const string angle = "Viewing Angle";
        private const string record = "Recording";
        private const string screenshot = "Take Screenshot";

        /**
         * Functions implemented from ICategory
         * 
         * Used to return the specific properties value as a List that this model contain back to the caller
         */
        public List<string> getCategoryProperties()
        {
            List<string> properties = new List<string>
            {
                status,
                angle,
                record,
                screenshot
            };

            return properties;
        }
    }
}

ICT2106_WithAction/Models/Cameras/CameraValue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Cameras
{
    class CameraValue : IPropertyValue
    {
        private List<string> propertyList;
        private List<string> propertyName;

        public CameraValue(List<string> propertyList, List<string> propertyName)
        {
            this.propertyList = propertyList;
            this.propertyName = propertyName;
        }

        public List<string> getPropertyList()
        {
            return propertyList;
        }

        public List<string> getPropertyName()
        {
            return propertyName;
        }
    }
}

ICT2106_WithAction/Models/Lightings/LightingFactory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Lightings
{
    public class LightingFactory : ICategoryFactory
    {
        public IGeneralValue setGeneralValue(int actionID, string actionName, string category, int deviceID, string deviceName)
        {
            return new LightingGeneral(actionID, actionName, category, deviceID, deviceName);
        }

        public IPropertyValue setPropertyValues(List<string> propertyList, List<string> propertyName)
        {
            return new LightingValue(propertyList, propertyName);
        }
    }
}

ICT2106_WithAction/Models/Lightings/LightingGeneral.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Lightings
{
    class LightingGeneral : IGeneralValue
    {
        private int actionID;
        private string actionName;
        private string category;
        private int deviceID;
        private string deviceName;

        public LightingGeneral(int actionID, string actionName, string category, int deviceID, string deviceName)
        {
            this.actionID = actionID;
            this.actionName = actionName;
            this.category = category;
            this.deviceID = deviceID;
            this.deviceName = deviceName;
        }

        public int getActionID()
        {
            return actionID;
        }

        public string getActionName()
        {
            return actionName;
        }

        public string getCategory()
        {
            return category;
        }

        public int getDeviceID()
        {
            return deviceID;
        }

        public string getDeviceName()
        {
            return deviceName;
        }
    }
}

ICT2106_WithAction/Models/Lightings/LightingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Lightings
{
    public class LightingModel: ICategoryPropertyType
    {
        private const string status = "Status";
        private const string brightness = "Brightness";
        private const string color = "Color";

        /**
         * Functions implemented from ICategory
         * 
         * Used to return the specific properties value as a List that this model contain back to the caller
         */
        public List<string> getCategoryProperties()
        {
            List<string> properties = new List<string>
            {
                status,
                brightness,
                color
            };

            return properties;
        }

        public void qwe()
        {
            Console.WriteLine("qwe");
        }
    }
}

ICT2106_WithAction/Models/Lightings/LightingValue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Lightings
{
    class LightingValue : IPropertyValue
    {
        private List<string> propertyList;
        private List<string> propertyName;

        public LightingValue(List<string> propertyList, List<string> propertyName)
        {
            this.propertyList = propertyList;
            this.propertyName = propertyName;
        }

        public List<string> getPropertyList()
        {
            return propertyList;
        }

        public List<string> getPropertyName()
        {
            return propertyName;
        }
    }
}

ICT2106_WithAction/Models/Securities/SecurityFactory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Securities
{
    public class SecurityFactory : ICategoryFactory
    {
        public IGeneralValue setGeneralValue(int actionID, string actionName, string category, int deviceID, string deviceName)
        {
            return new SecurityGeneral(actionID, actionName, category, deviceID, deviceName);
        }

        public IPropertyValue setPropertyValues(List<string> propertyList, List<string> propertyName)
        {
            return new SecurityValue(propertyList, propertyName);
        }
    }
}

ICT2106_WithAction/Models/Securities/SecurityGeneral.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Interfaces;

namespace ICT2106.Models.Securities
{
    class SecurityGeneral : IGeneralValue
    {
        private int actionID;
        private string actionName;
        private string category;
        private int deviceID;
        private string deviceName;

        public SecurityGeneral(int actionID, string actionName, string category, int deviceID, string deviceName)
        {
            this.actionID = actionID;
            this.actionName = actionName;
            this.category = category;
            this.deviceID = deviceID;
            this.deviceName = deviceName;
        }

        public int getActionID()
        {
            return actionID;
        }

        public string getActionName()
        {
            return actionName;
        }

        public string getCategory()
        {
            return category;
        }

        public int getDeviceID()
        {
            return deviceID;
        }

        public string getDeviceName()
        {
            return deviceName;
        }
    }
}

ICT2106_WithAction/Controllers/CategoryFormController.cs
using ICT2106.Interfaces;
using ICT2106.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ICT2106.Models.AirTreatment;
using ICT2106.Models.Cameras;
using ICT2106.Models.Lightings;
using ICT2106.Models.Securities;
using ICT2106.Models.Speakers;

namespace ICT2106.Controllers
{
    public class CategoryFormController : Controller
    {
        private ICategoryPropertyType _propertyInterface;
        private ICreateAction _createAction = new ActionModel();

        public IActionResult CreateLighting(string lightingName, string deviceId, string lightingStatus, string lightingBrightness, string lightingColor)
        {
            ActionGateway context = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;

            int deviceID = int.Parse(deviceId);
            string deviceName = context.getDeviceByID(deviceID);

            if (String.IsNullOrEmpty(lightingBrightness))
            {
                lightingBrightness = "50";
            }
            if (String.IsNullOrEmpty(lightingColor))
            {
                lightingColor = "White";
            }

            _propertyInterface = new LightingModel();
            List<string> propertyName = _propertyInterface.getCategoryProperties();
            List<string> propertyList = new List<string> { lightingStatus, lightingBrightness, lightingColor };


            ICategoryFactory factory = CategorySingleton.GetInstance().GetFactory("Lighting");
            IGeneralValue general = factory.setGeneralValue(-1, lightingName, "Lighting", deviceID, deviceName);
            IPropertyValue property = factory.setPropertyValues(propertyList, propertyName);

            _createAction.createAction(
                general.getActionID(),
                general.getActionName(),
                general.getCategory(),
                property.getPropertyList(),
                property.getPropertyName(),
                general.getDeviceID(),
                general.getDeviceName()
            );

            return RedirectToAction("ActionDisplay", "Action", (ActionModel)_createAction);
        }


        public IActionResult CreateCamera(string cameraName, string deviceId, string cameraStatus, string cameraViewingAngle, string cameraRecordingStatus, string cameraTakeScreenshot)
        {
            ActionGateway context = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;

            int deviceID = int.Parse(deviceId);
            string deviceName = context.getDeviceByID(deviceID);

            if (String.IsNullOrEmpty(cameraViewingAngle))
            {
                cameraViewingAngle = "180";
            }

            _propertyInterface = new CameraModel();
            List<string> propertyName = _propertyInterface.getCategoryProperties();
            List<string> propertyList = new List<string> { cameraStatus, cameraViewingAngle, cameraRecordingStatus, cameraTakeScreenshot };

            ICategoryFactory factory = CategorySingleton.GetInstance().GetFactory("Camera");
            IGeneralValue general = factory.setGeneralValue(-1, cameraName, "Camera", deviceID, deviceName);
            IPropertyValue property = factory.setPropertyValues(propertyList, propertyName);

            _createAction.createAction(
                general.getActionID(),
                general.getActionName(),
                general.getCategory(),
                property.getPropertyList(),
                property.getPropertyName(),
                general.getDeviceID(),
                general.getDeviceName()
            );

            return RedirectToAction("ActionDisplay", "Action", (ActionModel)_createAction);
        }

        public IActionResult CreateSecurity(string securityName, string deviceId, string securityStatus)
        {
            ActionGateway context = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;

            int deviceID = int.Parse(deviceId);
            string deviceName = context.getDeviceByID(deviceID);

            _propertyInterface = new SecurityModel();
            List<string> propertyName = _propertyInterface.getCategoryProperties();
            List<string> propertyList = new List<string> { securityStatus };

            ICategoryFactory factory = CategorySingleton.GetInstance().GetFactory("Security");
            IGeneralValue general = factory.setGeneralValue(-1, securityName, "Security", deviceID, deviceName);
            IPropertyValue property = factory.setPropertyValues(propertyList, propertyName);

            _createAction.createAction(
                general.getActionID(),
                general.getActionName(),
                general.getCategory(),
                property.getPropertyList(),
                property.getPropertyName(),
                general.getDeviceID(),
                general.getDeviceName()
            );

            return RedirectToAction("ActionDisplay", "Action", (ActionModel)_createAction);
        }

        public IActionResult CreateSpeaker(string actionName, string deviceId, string speakerStatus, string speakerService, string speakerPlaylist, string speakerSong, string speakerState, string speakerVolume)
        {

            if (String.IsNullOrEmpty(speakerPlaylist))
            {
                speakerPlaylist = "NIL";
            }
            if (String.IsNullOrEmpty(speakerSong))
            {
                speakerSong = "NIL";
            }
            if (String.IsNullOrEmpty(speakerVolume))
            {
                speakerVolume = "50";
            }

            ActionGateway context = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;

            int deviceID = int.Parse(deviceId);
            string deviceName = context.getDeviceByID(deviceID);

            _propertyInterface = new SpeakerModel();
            List<string> propertyName = _propertyInterface.getCategoryProperties();
            List<string> propertyList = new List<string> { speakerStatus, speakerService, speakerPlaylist, speakerSong, speakerState, speakerVolume };

            ICategoryFactory factory = CategorySingleton.GetInstance().GetFactory("Speaker");
            IGeneralValue general = factory.setGeneralValue(-1, actionName, "Speaker", deviceID, deviceName);
            IPropertyValue property = factory.setPropertyValues(propertyList, propertyName);

            _createAction.createAction(
                general.getActionID(),
                general.getActionName(),
                general.getCategory(),
                property.getPropertyList(),
                property.getPropertyName(),
                general.getDeviceID(),
                general.getDeviceName()
            );

            return RedirectToAction("ActionDisplay", "Action", (ActionModel)_createAction);
        }

        public IActionResult CreateAir(string actionName, string deviceId, string airStatus, string airSpeed, string airPan)
        {
            ActionGateway context = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;

            int deviceID = int.Parse(deviceId);
            string deviceName = context.getDeviceByID(deviceID);

            _propertyInterface = new AirModel();
            List<string> propertyName = _propertyInterface.getCategoryProperties();
            List<string> propertyList = new List<string> { airStatus, airSpeed, airPan };

            ICategoryFactory factory = CategorySingleton.GetInstance().GetFactory("Air Treatment");
            IGeneralValue general = factory.setGeneralValue(-1, actionName, "Air Treatment", deviceID, deviceName);
            IPropertyValue property = factory.setPropertyValues(propertyList, propertyName);

            _createAction.createAction(
                general.getActionID(),
                general.getActionName(),
                general.getCategory(),
                property.getPropertyList(),
                property.getPropertyName(),
                general.getDeviceID(),
                general.getDeviceName()
            );

            return RedirectToAction("ActionDisplay", "Action", (ActionModel)_createAction);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ICT2106_WithAction/Views/Action/AirForm.cshtml
@{
    var objList = ViewData["getAllDevices_Id_Name"] as List<object>;
    var getAllDevices_Id_Name = objList[0] as List<String>;
    var n = objList.Count;
}

<p>To use past configuration for this selected category of devices, please click <a href='@Url.Action("ActionQuickSelect", "Action", new { category = "Air Treatment" })'>here</a></p>
<br />

<!--
    The Html Page for Air Treatment Create Forms
-->

<form method="post" asp-controller="CategoryForm" asp-action="CreateAir">
    <div class="form-group">
        <label for="actionName">Action Name</label>
        <input type="text" class="form-control" id="actionName" name="actionName" placeholder="Enter Action Name" required>
    </div>

    <div class="form-group">
        <label for="deviceId">Choose a device</label>
        <select class="form-control" id="deviceId" name="deviceId">
            @foreach (String eachDevicePair in getAllDevices_Id_Name)
            {
                var deviceId = eachDevicePair.Split(",")[0];
                var deviceName = eachDevicePair.Split(",")[1];
                <option value=@deviceId>@deviceName</option>
            }

        </select>
    </div>

    @if (n == 2)
    {
        var quickSelectModel = objList[1] as ActionModel;

        @if (quickSelectModel.ACTIONPROPERTYLIST[0] != null)
        {
            <div class="form-group">
                <label for="airStatus">Air Treatment Status</label>
                <select class="form-control" id="airStatus" name="airStatus">
                    @if (quickSelectModel.ACTIONPROPERTYLIST[0] == "On")
                    {
                        <option value="On" selected>On</option>
                        <option value="Off">Off</option>
                    }
                    else
                    {
                        <option value="On">On</option>
                        <option value="Off" selected>Off</option>
                    }
                </select>
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="airStatus">Air Treatment Status</label>
                <select class="form-control" id="airStatus" name="airStatus">
                    <option value="On">On</option>
                    <option value="Off">Off</option>
                </select>
            </div>
        }

        @if (quickSelectModel.ACTIONPROPERTYLIST[1] != null)
        {
            <div class="form-group">
                <label for="airSpeed">Air Treatment Fan Speed</label>
                <select class="form-control" id="airSpeed" name="airSpeed">
                    @if (quickSelectModel.ACTIONPROPERTYLIST[1] == "Low")
                    {
                        <option value="Low" selected>Low</option>
                        <option value="Medium">Medium</option>
                        <option value="High">High</option>
                    }
                    else if (quickSelectModel.ACTIONPROPERTYLIST[1] == "Medium")
                    {
                        <option value="Low">Low</option>
                        <option value="Medium" selected>Medium</option>
                        <option value="High">High</option>
                    }
                    else
                    {
                        <option value="Low">Low</option>
                        <option value="Medium">Medium</option>
                        <option value="High" selected>High</option>
                    }
                </select>
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="airSpeed">Air Treatment Fan Speed</label>
                <select class="form-control" id="airSpeed" name="airSpeed">
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                </select>
            </div>
        }

        @if (quickSelectModel.ACTIONPROPERTYLIST[2] != null)
        {
            <div class="form-group">
                <label for="airPan">Air Treatment Auto Rotate</label>
                <select class="form-control" id="airPan" name="airPan">
                    @if (quickSelectModel.ACTIONPROPERTYLIST[2] == "On")
                    {
                        <option value="On" selected>On</option>
                        <option value="Off">Off</option>
                    }
                    else
                    {
                        <option value="On">On</option>
                        <option value="Off" selected>Off</option>
                    }
                </select>
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="airPan">Air Treatment Auto Rotate</label>
                <select class="form-control" id="airPan" name="airPan">
                    <option value="On">On</option>
                    <option value="Off">Off</option>
                </select>
            </div>
        }
    }
    else
    {
        <div class="form-group">
            <label for="airStatus">Air Treatment Status</label>
            <select class="form-control" id="airStatus" name="airStatus">
                <option value="On">On</option>
                <option value="Off">Off</option>
            </select>
        </div>

        <div class="form-group">
            <label for="airSpeed">Air Treatment Fan Speed</label>
            <select class="form-control" id="airSpeed" name="airSpeed">
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>
            </select>
        </div>

        <div class="form-group">
            <label for="airPan">Air Treatment Auto Rotate</label>
            <select class="form-control" id="airPan" name="airPan">
                <option value="On">On</option>
                <option value="Off">Off</option>
            </select>
        </div>
    }

    <button type="submit" onclick="return confirm('Are you sure you want to submit?');" class="btn btn-primary">Submit</button>
</form>

ICT2106_WithAction/Views/Action/CameraForm.cshtml
<!--

Value to edit when HttpPost Function is up else will get error in current form

-->
@{
    var objList = ViewData["getAllDevices_Id_Name"] as List<object>;
    var getAllDevices_Id_Name = objList[0] as List<String>;
    var n = objList.Count;
}

<p>To use past configuration for this selected category of devices, please click <a href='@Url.Action("ActionQuickSelect", "Action", new { category = "Camera" })'>here</a></p>
<br />

<!--
    The Html Page for Camera Create Forms
-->
<form method="post" asp-controller="CategoryForm" asp-action="CreateCamera">
    <div class="form-group">
        <label for="cameraName">Action Name</label>
        <input type="text" class="form-control" id="cameraName" name="cameraName" placeholder="Enter Action Name">
    </div>

    <div class="form-group">
        <label for="deviceId">Choose a device</label>
        <select class="form-control" id="deviceId" name="deviceId">
            @foreach (String eachDevicePair in getAllDevices_Id_Name)
            {
                var deviceId = eachDevicePair.Split(",")[0];
                var deviceName = eachDevicePair.Split(",")[1];
                <option value=@deviceId>@deviceName</option>
            }

        </select>
    </div>

    @if (n == 2)
    {
        var quickSelectModel = objList[1] as ActionModel;

        @if (quickSelectModel.ACTIONPROPERTYLIST[0] != null)
        {
            <div class="form-group">
                <label for="cameraStatus">Camera Status</label>
                <select class="form-control" id="cameraStatus" name="cameraStatus">
                    @if (quickSelectModel.ACTIONPROPERTYLIST[0] == "On")
                    {
                        <option value="On" selected>On</option>
                        <option value="Off">Off</option>
                    }
                    else
                    {
                        <option value="On">On</option>
                        <option value="Off" selected>Off</option>
                    }
                </select>
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="cameraStatus">Camera Status</label>
                <select class="form-control" id="cameraStatus" name="cameraStatus">
                    <option value="On">On</option>
                    <option value="Off">Off</option>
                </select>
            </div>
        }

        @if (quickSelectModel.ACTIONPROPERTYLIST[1] != null)
        {
            <div class="form-group">
                <label for="cameraViewingAngle">Camera Viewing Angle (360&deg;)</label>
                <input type="number" class="form-control" id="cameraViewingAngle" name="cameraViewingAngle" min="0" max="360" placeholder="Enter Camera Viewing Angle From 0 - 360" value="@quickSelectModel.ACTIONPROPERTYLIST[1]">
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="cameraViewingAngle">Camera Viewing Angle (360&deg;)</label>
                <input type="number" class="form-control" id="cameraViewingAngle" name="cameraViewingAngle" min="0" max="360" placeholder="Enter Camera Viewing Angle From 0 - 360">
            </div>
        }

        @if (quickSelectModel.ACTIONPROPERTYLIST[2] != null)
        {
            <div class="form-group">
                <label for="cameraRecordingStatus">Camera Recording Status</label>
                <select class="form-control" id="cameraRecordingStatus" name="cameraRecordingStatus">
                    @if (quickSelectModel.ACTIONPROPERTYLIST[2] == "Recording")
                    {
                        <option value="Recording" selected>Recording</option>
                        <option value="Not Recording">Not Recording</option>
                    }
                    else
                    {
                        <option value="Recording">Recording</option>
                        <option value="Not Recording" selected>Not Recording</option>
                    }
                </select>
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="cameraRecordingStatus">Camera Recording Status</label>
                <select class="form-control" id="cameraRecordingStatus" name="cameraRecordingStatus">
                    <option value="Recording">Recording</option>
                    <option value="Not Recording">Not Recording</option>
                </select>
            </div>
        }

        @if (quickSelectModel.ACTIONPROPERTYLIST[3] != null)
        {
            <div class="form-group">
                <label for="cameraTakeScreenshot">Take a screenshot?</label>
                <select class="form-control" id="cameraTakeScreenshot" name="cameraTakeScreenshot">
                    @if (quickSelectModel.ACTIONPROPERTYLIST[3] == "Yes")
                    {
                        <option value="Yes" selected>Yes</option>
                        <option value="No">No</option>
                    }
                    else
                    {
                        <option value="Yes">Yes</option>
                        <option value="No" selected>No</option>
                    }
                </select>
            </div>
        }
        else
        {
            <div class="form-group">
                <label for="cameraTakeScreenshot">Take a screenshot?</label>
                <select class="form-control" id="cameraTakeScreenshot" name="cameraTakeScreenshot">
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                </select>
            </div>
        }
    }
    else
    {
        <div class="form-group">
            <label for="cameraStatus">Camera Status</label>
            <select class="form-control" id="cameraStatus" name="cameraStatus">
                <option value="On">On</option>
                <option value="Off">Off</option>
            </select>
        </div>

        <div class="form-group">
            <label for="cameraViewingAngle">Camera Viewing Angle (360&deg;)</label>
            <input type="number" class="form-control" id="cameraViewingAngle" name="cameraViewingAngle" min="0" max="360" placeholder="Enter Camera Viewing Angle From 0 - 360">
        </div>

        <div class="form-group">
            <label for="cameraRecordingStatus">Camera Recording Status</label>
            <select class="form-control" id="cameraRecordingStatus" name="cameraRecordingStatus">
                <option value="Recording">Recording</option>
                <option value="Not Recording">Not Recording</option>
            </select>
        </div>

        <div class="form-group">
            <label for="cameraTakeScreenshot">Take a screenshot?</label>
            <select class="form-control" id="cameraTakeScreenshot" name="cameraTakeScreenshot">
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
    }

    <button type="submit" onclick="return confirm('Are you sure you want to submit?');" class="btn btn-primary">Submit</button>
</form>