ICT2106_WithAction/Controllers/ListenController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ICT2106.Models.Listeners;
using ICT2106.Models.ConditionTableModule;
using System.Threading;

namespace ICT2106.Controllers{
    public class listenController : Controller {
        
        public IActionResult ListenDisplay()
        {
            ListenerModel act = new ListenerModel();
            BothThreadList dList = new BothThreadList();
            dList = act.getDisplay();
            ViewData["ForDisplay"] = dList;   
            return View();
        }

        public IActionResult TerminateThread(string tid)
        {
            ListenerModel act = new ListenerModel();
            act.AbortThread(Int32.Parse(tid));
            Thread.Sleep(500);
            BothThreadList dList = new BothThreadList();
            dList = act.getDisplay();
            ViewData["ForDisplay"] = dList;
            Console.WriteLine("Return View");

            return View("ListenDisplay");
        }
        public IActionResult GetActions()
        {
            ListenerModel act = new ListenerModel();
            Condition con = new Condition();
            con.Devcat = 2;
            con.ConditionID = 34;
            act.ActionChecker(con);
            Condition con2 = new Condition();
            con2.Devcat = 2;
            con2.ConditionID = 33;
            act.ActionChecker(con2);
            BothThreadList dList = new BothThreadList();
            dList = act.getDisplay();
            ViewData["ForDisplay"] = dList;

            return View("ListenDisplay");
        }

    }
}

ICT2106_WithAction/Controllers/RuleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Text;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ICT2106.Models.RuleTableModule;
using ICT2106.Models.ConditionTableModule;
using ICT2106.Models.DevcatTableModule;
using ICT2106.Models.DevcondTableModule;
using ICT2106.Models.MotionDetailsModule;
using ICT2106.Models.TimerDetailsModule;
using ICT2106.Models.RuleSingleton;
using ICT2106.Models;
using ICT2106.Interfaces;

namespace ICT2106.Controllers
{
    public class RuleController : Controller
    {
        private readonly ILogger<RuleController> _logger;
        private IAction _action = new ActionModel();
        private ActionDAO _dao;

        //lists SINGLETON
        private RuleSingletonModel RS = RuleSingletonModel.getInstance();
        //gateways ADD ACTION GATEWAY HERE
        private RuleGateway rg = new RuleGateway();
        private ConditionGateway cg = new ConditionGateway();
        private devcatGateway dcat = new devcatGateway();
        private devcondGateway dcon = new devcondGateway();
        private motionDetailsGateway md = new motionDetailsGateway();
        private timerDetailsGateway td = new timerDetailsGateway();

        public RuleController(ILogger<RuleController> logger)
        {
            _logger = logger;
        }

        /*
        Still using a list of rules ADD ACTION STUFF IN RULES,RULEADD,RULEEDIT,RULEDELETE
        */
        public IActionResult Rules()
        {
            ActionModel create = _action.getActionInstance();
            TryUpdateModelAsync(create); // This is the asynchronous call to try to take data from the url into the ActionModel variable
            _dao = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;
            List<ActionModel> actionList = new List<ActionModel>();

            rg.GetAllRules();
            cg.GetAllCondition();
            dcat.GetAllCat();
            dcon.GetAllDev();
            md.GetAllMotion();
            td.GetAllTimer();
            foreach (IRule rule in RS.Rulelist)
            {
                _action = _dao.getAllActionFromDBUsingRuleID(rule.RuleID);
                actionList.Add((ActionModel)_action);

                foreach (ICondition condition in RS.Conditionlist)
                {
                    if (rule.RuleID == condition.RuleID)
                    {
                        rule.Condition = condition;
                    }
                }
            }

            ViewData["ActionList"] = actionList;
            ViewData["CatData"] = RS.Catlist;
            ViewData["ConData"] = RS.Devlist;
            ViewData["RuleData"] = RS.Rulelist;
            ViewData["MotionData"] = RS.Mdlist;
            ViewData["TimerData"] = RS.Tdlist;
            ViewData["ActionData"] = create;
            return View();
        }
        /*
        Now just taking a string input then pass it to gateway
        */
        public IActionResult RuleAdd(String addRule, String MCName, String CID, String MDCID, String HP, String PP, String TCName, String TDCID, String tm, List<string> actionDetails, List<string> actionProperties, List<string> actionPropertiesName)
        {
            ActionModel create = _action.getActionInstance();
            TryUpdateModelAsync(create); // This is the asynchronous call to try to take data from the url into the ActionModel variable
            _dao = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;
            List<ActionModel> actionList = new List<ActionModel>();

            int DevID = 0;
            int ruleID = rg.RuleAdd(addRule);
            if (CID == "1")
            {
                if (MDCID == "1")
                {
                    DevID = 2;
                }
                else if (MDCID == "2")
                {
                    DevID = 3;
                }
                cg.addNewCond(ruleID.ToString(), DevID.ToString(), MCName, CID, MDCID);
                md.InsertMotionDetails(MDCID, HP, PP);
            }
            else if (CID == "2")
            {
                if (TDCID == "3")
                {
                    DevID = 1;
                }
                else if (TDCID == "4")
                {
                    DevID = 2;
                }
                cg.addNewCond(ruleID.ToString(), DevID.ToString(), TCName, CID, TDCID);
                td.InsertTimerDetails(TDCID, tm);
            }

            ActionModel newAction = (ActionModel)_action;
            newAction.ACTIONNAME = actionDetails[0];
            newAction.ACTIONCATEGORY = actionDetails[2];
            newAction.DEVICEID = Int32.Parse(actionDetails[4]);
            newAction.ACTIONPROPERTYNAME = actionPropertiesName;
            newAction.ACTIONPROPERTYLIST = actionProperties;
            int no_of_affected_rows = _dao.saveActionToDB(newAction, ruleID);

            rg.GetAllRules();
            cg.GetAllCondition();
            dcat.GetAllCat();
            dcon.GetAllDev();
            md.GetAllMotion();
            td.GetAllTimer();
            foreach (IRule rule in RS.Rulelist)
            {
                _action = _dao.getAllActionFromDBUsingRuleID(rule.RuleID);
                actionList.Add((ActionModel)_action);

                foreach (ICondition condition in RS.Conditionlist)
                {
                    if (rule.RuleID == condition.RuleID)
                    {
                        rule.Condition = condition;
                    }
                }
            }

            ViewData["ActionList"] = actionList;
            ViewData["CatData"] = RS.Catlist;
            ViewData["ConData"] = RS.Devlist;
            ViewData["RuleData"] = RS.Rulelist;
            ViewData["MotionData"] = RS.Mdlist;
            ViewData["TimerData"] = RS.Tdlist;
            ViewData["ActionData"] = create;
            return View("Rules");
        }

        public IActionResult RuleEdit(String ruleIDEdit, String ruleNameEdit, String conIDEdit, String MCName, String CID, String MDCID, String HP, String PP, String TCName, String TDCID, String tm, List<string> actionDetails, List<string> actionProperties, List<string> actionPropertiesName)
        {
            _dao = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;
            List<ActionModel> actionList = new List<ActionModel>();

            int DevID = 0;
            rg.RuleEdit(ruleIDEdit, ruleNameEdit);
            if (CID == "1")
            {
                if (MDCID == "1")
                {
                    DevID = 2;
                }
                else if (MDCID == "2")
                {
                    DevID = 3;
                }
                cg.EditCondition(conIDEdit, DevID.ToString(), MCName, CID, MDCID);
                md.EditMotionDetails(conIDEdit, MDCID, HP, PP);
            }
            else if (CID == "2")
            {
                if (TDCID == "3")
                {
                    DevID = 1;
                }
                else if (TDCID == "4")
                {
                    DevID = 2;
                }
                cg.EditCondition(conIDEdit, DevID.ToString(), TCName, CID, TDCID);
                td.EditTimerDetails(conIDEdit, TDCID, tm);
            }

            ActionModel newAction = (ActionModel)_action;
            newAction.ACTIONNAME = actionDetails[0];
            newAction.ACTIONCATEGORY = actionDetails[2];
            newAction.DEVICEID = Int32.Parse(actionDetails[4]);
            newAction.ACTIONPROPERTYNAME = actionPropertiesName;
            newAction.ACTIONPROPERTYLIST = actionProperties;
            int no_of_affected_rows = _dao.updateActionWithRule(newAction, int.Parse(ruleIDEdit));



            rg.GetAllRules();
            cg.GetAllCondition();
            dcat.GetAllCat();
            dcon.GetAllDev();
            md.GetAllMotion();
            td.GetAllTimer();
            foreach (IRule rule in RS.Rulelist)
            {
                _action = _dao.getAllActionFromDBUsingRuleID(rule.RuleID);
                actionList.Add((ActionModel)_action);

                foreach (ICondition condition in RS.Conditionlist)
                {
                    if (rule.RuleID == condition.RuleID)
                    {
                        rule.Condition = condition;
                    }
                }
            }
            ViewData["ActionList"] = actionList;
            ViewData["CatData"] = RS.Catlist;
            ViewData["ConData"] = RS.Devlist;
            ViewData["RuleData"] = RS.Rulelist;
            ViewData["MotionData"] = RS.Mdlist;
            ViewData["TimerData"] = RS.Tdlist;
            return View("Rules");
        }
        /*
        Now just taking a string input then pass it to gateway
        */
        public IActionResult RuleDelete(String delcid, String delrid, String delcatid)
        {
            _dao = HttpContext.RequestServices.GetService(typeof(ActionGateway)) as ActionGateway;
            List<ActionModel> actionList = new List<ActionModel>();

            rg.RuleDelete(delrid);
            if (delcatid == "1")
            {
                cg.DeleteCondition(delcid);
                md.DeleteMotion(delcid);
            }
            else if (delcatid == "2")
            {
                cg.DeleteCondition(delcid);
                td.DeleteTimer(delcid);
            }

            int no_of_affected_rows = _dao.deleteActionFromDB(int.Parse(delrid));

            rg.GetAllRules();
            cg.GetAllCondition();
            dcat.GetAllCat();
            dcon.GetAllDev();
            md.GetAllMotion();
            td.GetAllTimer();
            foreach (IRule rule in RS.Rulelist)
            {
                _action = _dao.getAllActionFromDBUsingRuleID(rule.RuleID);
                actionList.Add((ActionModel)_action);

ICT2106_WithAction/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ICT2106</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ICT2106</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Something">Something</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rule" asp-action="Rules">View Rules</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="listen" asp-action="ListenDisplay">Listening Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Action" asp-action="ActionMain">Action</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ICT2106 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/ce8211e3e8.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>